In [112]:
import numpy as np

In [113]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [114]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [126]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [133]:
arr_2d[:2,:]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [134]:
arr = np.arange(1,11)

In [135]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
bool_arr= arr > 5

In [138]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [139]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [140]:
arr[arr<3]

array([1, 2])

In [143]:
arr_2d = np.arange(50).reshape(5,10)

In [144]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [146]:
arr= np.arange(0,11)

In [147]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [148]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [149]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
arr *arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [151]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [154]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [155]:
arr.sum()

55

In [161]:
1/arr

/Users/sid/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [158]:
arr.std()

3.1622776601683795

In [160]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [162]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [163]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [164]:
np.max(arr)

10

In [165]:
arr.max()

10

In [166]:
np.min(arr)

0

In [167]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [168]:
np.log(arr)

/Users/sid/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])